In [1]:
pip install bs4

Requirement already satisfied: bs4 in c:\users\santy\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\santy\anaconda3\lib\site-packages (from bs4) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\santy\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.3.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from urllib.request import urlopen
from bs4 import BeautifulSoup

all_quotes = []
for i in range(1, 11):
    url = f'https://quotes.toscrape.com/page/{i}/'
    page = urlopen(url)
    soup = BeautifulSoup(page, 'html.parser')
    quotes = soup.find_all('div', class_='quote')

    for quote in quotes:
        text = quote.find('span', class_='text').text
        author = quote.find('small', class_='author').text
        tags = quote.find('div', class_='tags').find_all('a')

        tags_list = []
        for tag in tags:
            tags_list.append(tag.text)

        single_quote = [text, author, tags_list]
        all_quotes.append(single_quote)

df = pd.DataFrame(all_quotes, columns=['quote', 'author', 'tags'])
df.to_csv('quotes.csv', index=False)

In [3]:
df

,quote,author,tags
0,“The world as we have created it is a process ...,Albert Einstein,"[change, deep-thoughts, thinking, world]"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"[abilities, choices]"
2,“There are only two ways to live your life. On...,Albert Einstein,"[inspirational, life, live, miracle, miracles]"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"[aliteracy, books, classic, humor]"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"[be-yourself, inspirational]"
...,...,...,...
95,“You never really understand a person until yo...,Harper Lee,[better-life-empathy]
96,“You have to write the book that wants to be w...,Madeleine L'Engle,"[books, children, difficult, grown-ups, write,..."
97,“Never tell the truth to people who are not wo...,Mark Twain,[truth]
98,"“A person's a person, no matter how small.”",Dr. Seuss,[inspirational]
99,“... a mind needs books as a sword needs a whe...,George R.R. Martin,"[books, mind]"

In [6]:
df1=pd.read_csv(r"D:\DIG\quates.csv")

In [7]:
df1

,Unnamed: 0,Quotes,Authors,Tags
0,0,“The world as we have created it is a process ...,Albert Einstein,"change,deep-thoughts,thinking,world"
1,1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"abilities,choices"
2,2,“There are only two ways to live your life. On...,Albert Einstein,"inspirational,life,live,miracle,miracles"
3,3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"aliteracy,books,classic,humor"
4,4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"be-yourself,inspirational"
...,...,...,...,...
85,85,“Some day you will be old enough to start read...,C.S. Lewis,"age,fairytales,growing-up"
86,86,“We are not necessarily doubting that God will...,C.S. Lewis,god
87,87,“The fear of death follows from the fear of li...,Mark Twain,"death,life"
88,88,“A lie can travel half way around the world wh...,Mark Twain,"misattributed-mark-twain,truth"
89,89,“I believe in Christianity as I believe that t...,C.S. Lewis,"christianity,faith,religion,sun"